//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleConApp.myWcfServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myWcfServices.IMathComponent")]
    public interface IMathComponent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathComponent/AddFunc", ReplyAction="http://tempuri.org/IMathComponent/AddFuncResponse")]
        double AddFunc(double v1, double v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathComponent/AddFunc", ReplyAction="http://tempuri.org/IMathComponent/AddFuncResponse")]
        System.Threading.Tasks.Task<double> AddFuncAsync(double v1, double v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathComponent/SubFunc", ReplyAction="http://tempuri.org/IMathComponent/SubFuncResponse")]
        double SubFunc(double v1, double v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathComponent/SubFunc", ReplyAction="http://tempuri.org/IMathComponent/SubFuncResponse")]
        System.Threading.Tasks.Task<double> SubFuncAsync(double v1, double v2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathComponentChannel : SampleConApp.myWcfServices.IMathComponent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathComponentClient : System.ServiceModel.ClientBase<SampleConApp.myWcfServices.IMathComponent>, SampleConApp.myWcfServices.IMathComponent {
        
        public MathComponentClient() {
        }
        
        public MathComponentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathComponentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathComponentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathComponentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddFunc(double v1, double v2) {
            return base.Channel.AddFunc(v1, v2);
        }
        
        public System.Threading.Tasks.Task<double> AddFuncAsync(double v1, double v2) {
            return base.Channel.AddFuncAsync(v1, v2);
        }
        
        public double SubFunc(double v1, double v2) {
            return base.Channel.SubFunc(v1, v2);
        }
        
        public System.Threading.Tasks.Task<double> SubFuncAsync(double v1, double v2) {
            return base.Channel.SubFuncAsync(v1, v2);
        }
    }
}
