using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using UIApplication.myServices;//WCF service reference...

namespace UIApplication
{
  /// <summary>
  /// Interaction logic for WcfMathClient.xaml
  /// </summary>
  public partial class WcfMathClient : Window
  {
    public WcfMathClient()
    {
      InitializeComponent();
    }

    //Event handler for the Button' Click event...
    private void btnAdd_Click(object sender, RoutedEventArgs e)
    {
      //The name of the proxy class that is generated by the .NET will be the name of the interface suffixed with Client and removal of the I in the interface.=>IX, the proxy class =>XClient. 
      var proxy = new MathComponentClient();
      var result = proxy.AddFunc(double.Parse(txtValue1.Text), double.Parse(txtValue2.Text));
      lblResult.Content = "The Result of this operation is " + result;
    }
  }
}
